# Generated by Django 4.1 on 2023-12-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='preco',
            field=models.CharField(max_length=50, verbose_name='Preco'),
        ),
    ]
