# Generated by Django 4.1 on 2023-12-04 06:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preco',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
