# Generated by Django 4.1 on 2023-12-05 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
