# Generated by Django 4.1 on 2023-12-05 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
    ]
