# Generated by Django 4.1 on 2023-12-05 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
