# Generated by Django 4.1 on 2023-12-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebidas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bebidasproduct',
            old_name='product',
            new_name='product_reference',
        ),
        migrations.AddField(
            model_name='bebidasproduct',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
    ]
