# Generated by Django 4.1 on 2023-12-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebidas', '0002_rename_product_bebidasproduct_product_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bebidasproduct',
            name='product_id',
            field=models.IntegerField(),
        ),
    ]
