# Generated by Django 4.1 on 2023-12-08 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bebidas', '0003_alter_bebidasproduct_product_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bebidasproduct',
            options={'ordering': ['id'], 'verbose_name': 'Bebidas'},
        ),
    ]
