# Generated by Django 4.1 on 2023-12-08 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bebidas', '0004_alter_bebidasproduct_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bebidasproduct',
            options={},
        ),
    ]
